# .github/workflows/main.yml
name: github-workflow

on:
  workflow_call:
    inputs:
      docker_repo:
        description: 'Docker repository name'
        required: true
        type: string
      helm_repo:
        description: 'Helm chart repository'
        required: true
        type: string
      deploy_on_cluster:
        description: 'Boolean flag to deploy on cluster'
        required: false
        type: boolean
        default: true

    secrets:
      DOCKER_USERNAME:
        description: 'Docker Hub username'
        required: true
      DOCKER_PASSWORD:
        description: 'Docker Hub password'
        required: true
      PERSONAL_ACCESS_TOKEN:
        description: 'GitHub Personal Access Token'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Image Name
        id: image-name
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "IMAGENAME=${{ inputs.docker_repo }}-prod" >> $GITHUB_ENV
          else
            echo "IMAGENAME=${{ inputs.docker_repo }}" >> $GITHUB_ENV
          fi

      - name: Build Docker Image
        run: |
          VERSION="v1.0.${{ github.run_number }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          docker build --tag outreachgenius/${{ env.IMAGENAME }}:$VERSION .

      - name: Push Docker Image
        run: |
          VERSION=${{ env.VERSION }}
          docker push outreachgenius/${{ env.IMAGENAME }}:$VERSION
          docker tag outreachgenius/${{ env.IMAGENAME }}:$VERSION outreachgenius/${{ env.IMAGENAME }}:latest
          docker push outreachgenius/${{ env.IMAGENAME }}:latest

      - name: Output Docker Image Version
        run: |
          echo "Docker image built and pushed with version: $VERSION"

      - name: Clone Helm Repository
        if: ${{ inputs.deploy_on_cluster }}
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.helm_repo }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: main

      - name: Determine Environment and Directory
        id: env-check
        if: ${{ inputs.deploy_on_cluster }}
        run: |
          branch=${{ github.ref_name }}
          if [[ "$branch" == "main" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "DIRECTORY=production/${{ inputs.docker_repo }}" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "DIRECTORY=staging/${{ inputs.docker_repo }}" >> $GITHUB_ENV
          fi

      - name: Update Helm Chart values.yaml
        if: ${{ inputs.deploy_on_cluster }}
        run: |
          cd ${{ env.DIRECTORY }}
          sed -i "s/tag: .*/tag: $VERSION/" values.yaml

      - name: Commit and Push Changes
        if: ${{ inputs.deploy_on_cluster }}
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ${{ env.DIRECTORY }}/values.yaml
          git commit -m "Update Docker image tag to $VERSION"
          git push origin main
